//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submarca
    {
        public int id_submarca { get; set; }
        public string submarca1 { get; set; }
        public int id_marca { get; set; }
    }
}
